# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20180218_0236'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tags',
            field=models.ForeignKey(blank=True, max_length=60, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.TAGPersonal'),
        ),
    ]
