# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 21:26
from __future__ import unicode_literals

import apps.documentos.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('anotador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asunto', models.CharField(blank=True, default='', max_length=60)),
                ('materia', models.CharField(blank=True, default='', max_length=60)),
                ('organo_jurisdiccional', models.CharField(blank=True, default='', max_length=60)),
                ('texto_html', models.TextField(blank=True, default='', max_length=300000, null=True)),
                ('archivo', models.FileField(upload_to=apps.documentos.models.get_documento_path)),
                ('juez', models.CharField(blank=True, default='', max_length=80)),
                ('secretario', models.CharField(blank=True, default='', max_length=80)),
                ('preambulo', models.CharField(blank=True, default='', max_length=80)),
                ('resultandos', models.CharField(blank=True, default='', max_length=80)),
                ('considerandos', models.CharField(blank=True, default='', max_length=80)),
                ('puntos_resolutivos', models.CharField(blank=True, default='', max_length=80)),
                ('nombre_publico', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='DummyParrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionParrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creacion/actualizacion de la oracion')),
                ('tipo_anotacion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('texto', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_parrado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anotacion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('texto', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('is_correcta', models.BooleanField(default=True)),
                ('anotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oraciones', to='documentos.Anotacion')),
                ('evaluado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.IntegerField(blank=True, help_text='Indice de inicio delas palabras', null=True)),
                ('numero_final', models.IntegerField(blank=True, help_text='Indice de inicio delas palabras', null=True)),
                ('texto', django.contrib.postgres.fields.jsonb.JSONField()),
                ('ha_sido_evaluado', models.BooleanField(default=False, help_text='Marcar cuando un parrafo ya ha sido evaluado')),
                ('tipo', models.CharField(blank=True, help_text='Saber si es considerando, resultando, resuelve, etc.', max_length=40, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrafo', to='documentos.Documento')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Clasificacion')),
                ('subtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.TAG')),
            ],
        ),
        migrations.CreateModel(
            name='TAGPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.TAG')),
            ],
        ),
        migrations.AddField(
            model_name='oracion',
            name='parrafo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oraciones', to='documentos.Parrafo'),
        ),
        migrations.AddField(
            model_name='oracion',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='oraciones', to='documentos.TAG'),
        ),
        migrations.AddField(
            model_name='evaluacionparrafo',
            name='oracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='documentos.Oracion'),
        ),
        migrations.AddField(
            model_name='evaluacionparrafo',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_evaluacion', to='documentos.TAG'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacion', to='documentos.Documento'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
