# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-14 07:16
from __future__ import unicode_literals

import apps.documentos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asunto', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('materia', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('organo_jurisdiccional', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('texto_html', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('archivo', models.FileField(upload_to=apps.documentos.models.get_documento_path)),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='anotacion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacion', to='documentos.Documento'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
