# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-02 05:48
from __future__ import unicode_literals

import apps.documentos.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('anotador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_asunto', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('materia', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('organo_jurisdiccional', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('texto_html', models.TextField(blank=True, default='', max_length=300000, null=True)),
                ('archivo', models.FileField(upload_to=apps.documentos.models.get_documento_path)),
                ('juez', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('secretario', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('preambulo', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('resultandos', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('considerandos', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('puntos_resolutivos', models.CharField(blank=True, default='', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DummyParrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Parrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inicial', models.IntegerField(blank=True, help_text='Indice de inicio delas palabras', null=True)),
                ('numero_final', models.IntegerField(blank=True, help_text='Indice de inicio delas palabras', null=True)),
                ('texto', models.TextField(blank=True, max_length=10000, null=True)),
                ('ha_sido_evaluado', models.BooleanField(default=False, help_text='Marcar cuando un parrafo ya ha sido evaluado')),
                ('tipo', models.CharField(blank=True, help_text='Saber si es considerando, resultando, resuelve, etc.', max_length=40, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrafo', to='documentos.Documento')),
            ],
        ),
        migrations.CreateModel(
            name='TAG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.Clasificacion')),
                ('subtag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentos.TAG')),
            ],
        ),
        migrations.AddField(
            model_name='anotacion',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotacion', to='documentos.Documento'),
        ),
        migrations.AddField(
            model_name='anotacion',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
