# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-07 20:44
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_anotacion', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('texto', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('is_correcta', models.BooleanField(default=True)),
                ('anotacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oraciones', to='documentos.Anotacion')),
                ('evaluado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='parrafo',
            name='texto',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oracion',
            name='parrafo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oraciones', to='documentos.Parrafo'),
        ),
        migrations.AddField(
            model_name='oracion',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='documentos.TAG'),
        ),
    ]
