# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-21 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_auto_20171120_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='anotacion',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
