# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_oracion_clasificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clasificacion',
            old_name='texto',
            new_name='key',
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='nombre_publico',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
    ]
