# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_evaluacionparrafo_clasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacionparrafo',
            name='tags',
        ),
        migrations.AddField(
            model_name='evaluacionparrafo',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags_evaluacion', to='documentos.TAG'),
        ),
    ]
