# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_auto_20180208_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAGPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=50, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentos.TAG')),
            ],
        ),
        migrations.AlterModelOptions(
            name='parrafo',
            options={'ordering': ['id']},
        ),
    ]
