# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_auto_20180218_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='considerandos',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='documento',
            name='juez',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='documento',
            name='preambulo',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='documento',
            name='puntos_resolutivos',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resultandos',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='documento',
            name='secretario',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
