# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 00:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0006_auto_20180224_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentacionParrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField()),
                ('autor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='argumento', to=settings.AUTH_USER_MODEL)),
                ('parrafo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argumentacion', to='documentos.Parrafo')),
            ],
        ),
    ]
