# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_argumentacionparrafo'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentacionparrafo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de la evaluacion'),
        ),
    ]
