# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_auto_20180219_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='materia',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='documento',
            name='organo_jurisdiccional',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo_asunto',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
