# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 09:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_argumentacionparrafo_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentacionparrafo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='argumento', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='argumentacionparrafo',
            name='parrafo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='argumentacion', to='documentos.Parrafo'),
        ),
    ]
