# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_auto_20180219_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='nombre_publico',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
